### ISSUE TITLE
PDF needs link to website

### ISSUE THREAD

**Issue by bitcoinhodler** [joaofnfernandes/glacierprotocol.github.io#11]
The PDF currently has no reference to the main website glacierprotocol.org

**Comment by joaofnfernandes** [comment]
Fixed via 3df25a29ae65e7ac8e5b06b860c48a3b6b5b2e40

**Comment by bitcoinhodler** [comment]
What is this "Check the latest version/" text? That doesn't belong there...just the URL is sufficient.
