### ISSUE TITLE
File issue and PR buttons are hidden

### ISSUE THREAD

**Issue by joaofnfernandes** [joaofnfernandes/glacierprotocol.github.io#4]
These buttons are at the end of each page, so users will have a hard time finding them.
Try to move them to the beginning of the page.

**Comment by bitcoinhodler** [comment]
I also think it would be useful to have the section numbers appear on the site, in addition to the PDF, so that when a user finds an issue in the printed copy they can more easily find the appropriate page online to file an issue.

**Comment by joaofnfernandes** [comment]
I'll fork the issue about section numbers into another issue.
Fixed via fab96d759a23370acd07447cb9e38fa67c205444
