### ISSUE TITLE
Latest website updates missing from new site

### ISSUE THREAD

**Issue by bitcoinhodler** [joaofnfernandes/glacierprotocol.github.io#8]
The latest errata and release notes from https://github.com/GlacierProtocol/glacierprotocol.github.io/pull/1 are not included in this new site redo

**Comment by bitcoinhodler** [comment]
I see the errata have moved to the GitHub releases, so never mind on that part. The release notes are still in the PDF and are out of date.

Should the release notes remain in the PDF? There is some security advantage to having them there (since the PDF is signed and verified).

**Comment by joaofnfernandes** [comment]
You're right, this was also an oversight. Both the website and PDF were still mentioning the release notes, but it doesn't make sense to keep them.

To execute the protocol, users should always get the latest Glacier package (PDFs+scripts), and check the release notes for that version of the package.
For that reason I want to keep all that in a single place that users can trust - the Github releases page.

Also, when a new version is released, the team doesn't have to remember to update the site.

So:
* The site now has a `/downloads` page that will send users to the latest GH release
* Users can read the release notes and known issues there
* They can download the signed packages there

Fixed via 0c375784b37bc15394bc097ab9b595f552b80c3b

**Comment by bitcoinhodler** [comment]
In two places (4.1 step 1 and 5.1 step 1) the instructions say to look in the full-release PDF for the release notes.

Do you think the original authors had a reason for sending users to the PDF instead of the website?

**Comment by bitcoinhodler** [comment]
There's another mention in 6.2 about using the full release PDF to find release notes.

**Comment by joaofnfernandes** [comment]
I think that wasn't driven by security concerns, but by the historical artifact that release notes only existed in the PDF.

The Github releases page is served with HTTPs. So if you trust the project maintainers, you can trust the release notes in that page.

About sections 4.1, 5.1, and 6.2, I think that's a good example of sections that need to be updated after the new site is live. The protocol was written assuming that you could only get this information from the PDF, so it tells new users to check the site to see if there are new versions and things like that.

Once the new site goes live, new users should always be using the site to learn the protocol. So we'll be able to clean the protocol itself to reflect that.

**Comment by bitcoinhodler** [comment]
Not true. The release notes have always been on the website, accompanied by this notice:

> Note: The release notes below (and the release notes in the document-only releases) are provided for convenient, non-security-critical reference only. They are not secured with signed checksums, and therefore are not canonical. The canonical release notes are in the document appendices within the full Glacier releases, linked above.
> 
> If you are referencing release notes as directed by Glacier protocol itself, you should refer to the canonical notes in the protocol document itself rather than the notes here. The appropriate steps are listed in the protocol.

Clearly, there is a security concern here.

> The Github releases page is served with HTTPs. So if you trust the project maintainers, you can trust the release notes in that page.

This is a very concerning statement. Trusting the project maintainers is insufficient. If that was sufficient, the entire verification process using GPG and keybase.io would be pointless, because the website was always HTTPS. But it's far easier for a hacker to infiltrate and corrupt a website than forge a GPG signature that was done with a well-secured private key.

Glacier is nothing if not serious about security. I hope you also take security seriously.

Regarding sections 4.1, 5.1, and 6.2, there are two considerations. One, new users coming to the site. Assuming this doc and pdf go live and into a new release, these instructions are broken. You are willing to go live with a known-to-be-broken protocol? Two, there will be users with an old printout who are returning to withdraw their coins. Following their old printout, they will download the latest release, and find no release notes in the new PDF.

Removing the release notes from the PDF is both a security and usability issue.

**Comment by diogomonica** [comment]
@bitcoinhodler I understand your concerns and don't see a big problem with adding the notes to the PDF, but claiming that this protocol wouldn't be taking security seriously if the release notes aren't part of it is an overstatement, in my opinion.

> Trusting the project maintainers is insufficient. If that was sufficient, the entire verification process using GPG and keybase.io would be pointless, because the website was always HTTPS.

I agree with the general sentiment of not trusting the project maintainers, but the potential impact of attacker-controlled release-notes is significantly lower than attacker-controlled code or PDF. To be clear: we should always strive to have the safest protocol, but I read this argument as an all-or-nothing stance on security which I don't think we should adopt.

**Comment by bitcoinhodler** [comment]
I am not saying it's all-or-nothing; I am saying that this is a security downgrade, and as such should not be made with such a cavalier attitude. That @joaofnfernandes did not realize it was a security downgrade is concerning because it shows that he does not fully understand Glacier's security model.

If the maintainers do take security seriously, then any change like this one that has even the potential to affect security should not be made without careful and thorough review, which this change did not have.
